name: Maven Build and Release

on:
  release:
    types: [ created ]  # Trigger when a new release is created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Extract GitHub release tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update Maven project version
        run: mvn versions:set -DnewVersion=${{ env.RELEASE_VERSION }} -DprocessAllModules=true
        # The flag '-DprocessAllModules=true' will update all modules in a multi-module project

      - name: Maven Clean Install
        run: mvn clean install

      - name: Upload JAR files to GitHub Release
        env: # Add this line
          GITHUB_TOKEN: ${{ secrets.PAT }}  # Add this line
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }} # Provided by GitHub release event
          asset_path: ./target/zmBook-${{ env.RELEASE_VERSION }}.jar # Replace with your JAR file path
          asset_name: zmBook-${{ env.RELEASE_VERSION }}.jar  # Replace with your JAR file name
          asset_content_type: application/java-archive
